ALTER TABLE  `p_cups` ADD  `name` VARCHAR( 128 ) NOT NULL AFTER  `parent_cup_id` ;

UPDATE `p_cups` SET `name`='Группа I' WHERE `id`=4;
UPDATE `p_cups` SET `name`='Группа II' WHERE `id`=5;
UPDATE `p_cups` SET `name`='Группа А' WHERE `id`=8;
UPDATE `p_cups` SET `name`='Группа Б' WHERE `id`=9;
UPDATE `p_cups` SET `name`='Группа В' WHERE `id`=10;
UPDATE `p_cups` SET `name`='Группа 1' WHERE `id`=12;
UPDATE `p_cups` SET `name`='Группа 2' WHERE `id`=13;
UPDATE `p_cups` SET `name`='Группа 3' WHERE `id`=14;
UPDATE `p_cups` SET `name`='Группа 4' WHERE `id`=15;
UPDATE `p_cups` SET `name`='Группа А' WHERE `id`=17;
UPDATE `p_cups` SET `name`='Группа Б' WHERE `id`=18;
UPDATE `p_cups` SET `name`='Группа А' WHERE `id`=20;
UPDATE `p_cups` SET `name`='Группа Б' WHERE `id`=21;
UPDATE `p_cups` SET `name`='Группа В' WHERE `id`=22;
UPDATE `p_cups` SET `name`='Группа А' WHERE `id`=24;
UPDATE `p_cups` SET `name`='Группа Б' WHERE `id`=25;
UPDATE `p_cups` SET `name`='Группа А' WHERE `id`=27;
UPDATE `p_cups` SET `name`='Группа Б' WHERE `id`=28;
UPDATE `p_cups` SET `name`='Группа А' WHERE `id`=32;
UPDATE `p_cups` SET `name`='Группа Б' WHERE `id`=33;
UPDATE `p_cups` SET `name`='Группа В' WHERE `id`=34;
UPDATE `p_cups` SET `name`='Группа Г' WHERE `id`=35;
UPDATE `p_cups` SET `name`='Группа &Theta; / I' WHERE `id`=37;
UPDATE `p_cups` SET `name`='Группа &Lambda; / I' WHERE `id`=38;
UPDATE `p_cups` SET `name`='Группа &Xi; / II' WHERE `id`=39;
UPDATE `p_cups` SET `name`='Группа &Sigma; / I' WHERE `id`=40;
UPDATE `p_cups` SET `name`='Группа &Psi; / II' WHERE `id`=41;
UPDATE `p_cups` SET `name`='Группа &Omega; / II' WHERE `id`=42;
UPDATE `p_cups` SET `name`='Группа А' WHERE `id`=45;
UPDATE `p_cups` SET `name`='Группа Б' WHERE `id`=46;
UPDATE `p_cups` SET `name`='Группа В' WHERE `id`=47;
UPDATE `p_cups` SET `name`='Группа Г' WHERE `id`=48;
UPDATE `p_cups` SET `name`='Группа А' WHERE `id`=50;
UPDATE `p_cups` SET `name`='Группа Б' WHERE `id`=51;
UPDATE `p_cups` SET `name`='Группа В' WHERE `id`=52;
UPDATE `p_cups` SET `name`='Группа Г' WHERE `id`=53;
UPDATE `p_cups` SET `name`='Группа А' WHERE `id`=55;
UPDATE `p_cups` SET `name`='Группа Б' WHERE `id`=56;
UPDATE `p_cups` SET `name`='Группа В' WHERE `id`=57;
UPDATE `p_cups` SET `name`='Группа Г' WHERE `id`=58;