// ==ClosureCompiler==
// @compilation_level SIMPLE_OPTIMIZATIONS
// @output_file_name all.js
// @code_url http://pipeinpipe.info/js/lib-structures.js
// @code_url http://pipeinpipe.info/js/api.js
// @code_url http://pipeinpipe.info/js/common.js
// @code_url http://pipeinpipe.info/js/error-handler.js
// @code_url http://pipeinpipe.info/js/ui-controls.js
// @code_url http://pipeinpipe.info/js/ui-boxes.js
// @code_url http://pipeinpipe.info/js/content.js
// @code_url http://pipeinpipe.info/js/menu.js
// @code_url http://pipeinpipe.info/js/error.js
// @code_url http://pipeinpipe.info/js/main.js
// @formatting print_input_delimiter
// ==/ClosureCompiler==

// Input 0
function Stack(){return{head:null,push:function(a){var b=new __List;b.next=this.head;b.data=a;this.head=b},top:function(){return this.head.data},pop:function(){null!=this.head&&(this.head=this.head.next)},empty:function(){return null==this.head}}}
function Queue(){return{head:null,tail:null,add:function(a){var b=new __List;b.data=a;null==this.tail?this.head=this.tail=b:this.tail=this.tail.next=b},get:function(){var a=this.head.data;this.head=null!=this.head.next?this.head.next:this.tail=null;return a},print:function(){for(var a=this.head,b="";null!=a;)b+=a.data+" -> ",a=a.next;return b},empty:function(){return null==this.head}}}function __List(){return{next:null,data:null}}
function SuffixTree(a){void 0==a&&(a=[]);for(var b={stringArray:a,root:new __SuffixTreeNode,addString:function(b){if(!(0>b||b>=a.length))for(var c,e=a[b],h=0;h<e.length;h++){c=this.root;for(var f=h;f<e.length;f++)c=c.addChild(e.charAt(f));f=new __List;f.next=c.index;f.data=b;c.index=f}},getPossibleIndexes:function(b){if(void 0==b)return[];var c=Array(a.length),e=[],h;for(h=0;h<e.length;++h)e=!1;var f=this.root;for(h=0;h<b.length;++h)if(f=f.findChild(b.charAt(h)),null==f)return e;if(null!=f.index)for(b=
f.index;null!=b;)c[b.data]=!0,e.push(b.data),b=b.next;null!=f.child&&f.child.dfs(e,c);return e}},c=0;c<a.length;++c)b.addString(c);return b}
function __SuffixTreeNode(){return{child:null,next:null,data:"#",terminal:"#",index:null,addChild:function(a){var b;if(null==this.child)b=new __SuffixTreeNode,b.data=a,this.child=b;else if(a<this.child.data)b=new __SuffixTreeNode,b.next=this.child,b.data=a,this.child=b;else if(a==this.child.data)b=this.child;else for(var c=this.child;;){if(null==c.next||a<c.next.data){b=new __SuffixTreeNode;b.data=a;b.next=c.next;c.next=b;break}if(a==c.next.data){b=c.next;break}c=c.next}return b},findChild:function(a){var b;
if(null==this.child||a<this.child.data)return null;if(a==this.child.data)b=this.child;else for(var c=this.child;;){if(null==c.next||a<c.next.data)return null;if(a==c.next.data){b=c.next;break}c=c.next}return b},dfs:function(a,b){if(null!=this.index)for(var c=this.index;null!=c;)b[c.data]||(a.push(c.data),b[c.data]=!0),c=c.next;null!=this.child&&this.child.dfs(a,b);null!=this.next&&this.next.dfs(a,b)}}};
// Input 1
var api={__queue:new Queue,__cycling:!1,__number:1,__requested:{},TIMEOUT:250,URL:"/api.php",__init:function(){api.__queue=new Queue;api.__process()},__process:function(){if(!api.__queue.empty()){var a=api.__queue.get(),b=!0;debug("[api] task-"+a.number+" processing started");if(a.preventRepeating){var c=a.handler+"/"+a.method+"/",d;for(d in a.data)a.data.hasOwnProperty(d)&&(c+=d+"="+a.data[d]);api.__requested[c]&&(debug("[api] task-"+a.number+" processing is a repeating of "+api.__requested[c]+", so we do not execute it"),
b=!1);api.__requested[c]=a.number}b&&(b={url:api.URL,data:{handler:a.handler,method:a.method},dataType:a.dataType?a.dataType:"json",cache:!1,success:function(b){if((!b.status||"ok"==b.status)&&a.success)debug("[api] task-"+a.number+" succeeded"),a.success(b);b.retry&&(debug("[api] task-"+a.number+" retry"),api.request(a))},error:a.error?a.error:function(){debug("[api] task-"+a.number+" error")},async:void 0!==a.async?a.async:!0},$.extend(b.data,a.data),$.ajax(b),debug("[api] task-"+a.number+" processing finished"))}setTimeout(api.__process,
api.TIMEOUT);return!0},request:function(a){a.number||(a.number=api.__number++);api.__queue.add(a);debug("[api] task-"+a.number+" added: handler="+a.handler+"&method="+a.method);a.beforeSend&&a.beforeSend()}};$(api.__init());
// Input 2
var CONFIG={DEBUG:!0},COLOR={FIRST:"#007ca7",FIRST_LIGHT:"#c7dce3",SECOND:"#8fbc13",SECOND_LIGHT:"#b8d46c",THIRD:"#8fbc13",THIRD_LIGHT:"#c4a1bf"},common={cookies:{},cookiesInitialized:!1,params:{},paramsInitialized:!1,months:[{name:"\u042f\u043d\u0432\u0430\u0440\u044c",name_gen:"\u044f\u043d\u0432\u0430\u0440\u044f",name_short:"\u044f\u043d\u0432",length:31,length_leap:31},{name:"\u0424\u0435\u0432\u0440\u0430\u043b\u044c",name_gen:"\u0444\u0435\u0432\u0440\u0430\u043b\u044f",name_short:"\u0444\u0435\u0432",
length:28,length_leap:29},{name:"\u041c\u0430\u0440\u0442",name_gen:"\u043c\u0430\u0440\u0442\u0430",name_short:"\u043c\u0430\u0440",length:31,length_leap:31},{name:"\u0410\u043f\u0440\u0435\u043b\u044c",name_gen:"\u0430\u043f\u0440\u0435\u043b\u044f",name_short:"\u0430\u043f\u0440",length:30,length_leap:30},{name:"\u041c\u0430\u0439",name_gen:"\u043c\u0430\u044f",name_short:"\u043c\u0430\u0439",length:31,length_leap:31},{name:"\u0418\u044e\u043d\u044c",name_gen:"\u0438\u044e\u043d\u044f",name_short:"\u0438\u044e\u043d",
length:30,length_leap:30},{name:"\u0418\u044e\u043b\u044c",name_gen:"\u0438\u044e\u043b\u044f",name_short:"\u0438\u044e\u043b",length:31,length_leap:31},{name:"\u0410\u0432\u0433\u0443\u0441\u0442",name_gen:"\u0430\u0432\u0433\u0443\u0441\u0442\u0430",name_short:"\u0430\u0432\u0433",length:31,length_leap:31},{name:"\u0421\u0435\u043d\u0442\u044f\u0431\u0440\u044c",name_gen:"\u0441\u0435\u043d\u0442\u044f\u0431\u0440\u044f",name_short:"\u0441\u0435\u043d",length:30,length_leap:30},{name:"\u041e\u043a\u0442\u044f\u0431\u0440\u044c",
name_gen:"\u043e\u043a\u0442\u044f\u0431\u0440\u044f",name_short:"\u043e\u043a\u0442",length:31,length_leap:31},{name:"\u041d\u043e\u044f\u0431\u0440\u044c",name_gen:"\u043d\u043e\u044f\u0431\u0440\u044f",name_short:"\u043d\u043e\u044f",length:30,length_leap:30},{name:"\u0414\u0435\u043a\u0430\u0431\u0440\u044c",name_gen:"\u0434\u0435\u043a\u0430\u0431\u0440\u044f",name_short:"\u0434\u0435\u043a",length:31,length_leap:31}],monthDaysCount:function(a){var b=a.getFullYear(),b=0==b%4&&0!=b%100||0==b%
400,a=this.months[a.getMonth()];return b?a.length_leap:a.length},monthName:function(a){return this.months[a.getMonth()].name}};function ce(a){return document.createElement(a)}function ge(a){return document.getElementById(a)}function gtm(){return(new Date).getMilliseconds()}function tm(){return(new Date).getTime()}common.startTime=tm();
function initCookies(){common.cookies={};for(var a=document.cookie.split(";"),b=/^[\s]*([^\s]+?)$/i,c=0;c<a.length;c++){var d=a[c].split("=");2==d.length&&(common.cookies[d[0].match(b)[1]]=unescape(d[1].match(b)?d[1].match(b)[1]:""))}}function getCookie(a){common.cookiesInitialized||initCookies();return void 0!=common.cookies[a]?common.cookies[a]:null}
function setCookie(a,b,c){common.cookiesInitialized||initCookies();common.cookies[a]=b;if(c){var d=new Date;d.setTime(d.getTime()+864E5*c);c="; expires="+d.toGMTString()}else c="";d=location.host.match(/[^.]+\.[^.]+$/);document.cookie=a+"="+escape(b)+c+"; path=/"+(d?"; domain=."+d:"")}
function debug(a){try{for(var b=(tm()-common.startTime)/1E3+"",c=b.split(".",2),d="",g=0;g<5-c[0].length;++g)d+=" ";d+=b;for(b=0;b<3-c[1].length;++b)d+="0";CONFIG.DEBUG&&("string"===typeof a||"number"==typeof a?console&&console.debug(""+d+": "+a):(console&&console.debug(""+d+": Object!"),console&&console.debug(a)))}catch(e){}}function loadScript(a){var b=ce("script");b.src="/js/"+a+".js";document.getElementsByTagName("head")[0].appendChild(b)}var params={},paramsInitialized=!1;
function initAnchorParams(){common.params={};var a=document.URL;if(0<=a.indexOf("#"))for(var a=a.split("#")[1].split("&"),b=0;b<a.length;b++){var c=a[b].split("=");common.params[c[0]]=unescape(c[1])}paramsInitialized=!0}function getAnchorParam(a){common.paramsInitialized||initAnchorParams();return void 0==common.params[a]?null:common.params[a]}function setAnchorParam(a,b){common.paramsInitialized||initAnchorParams();common.params[a]=b;setAnchorParams()}
function getAnchorParams(){common.paramsInitialized||initAnchorParams();return common.params}function setAnchorParams(){var a="",b;for(b in common.params)b&&(a+="&"+b+"="+common.params[b]);0<a.length&&(a=a.substr(1,a.length-1));window.location=document.URL.split("#")[0]+"#"+a}function getKeys(a){var b=[],c;for(c in a)b.push(c);return b}function getTrueKeys(a){var b=[],c;for(c in a)a[c]&&b.push(c);return b}
function loading(a,b,c,d,g){a instanceof jQuery||(a=$(a));if(b){var b=a.innerWidth(),e=a.innerHeight(),h=$("<div/>").addClass("loading");g?h.css({top:void 0==d?(e-20)/2:d,left:void 0==c?(b-100)/2:c}).appendTo(a):(a=a.offset(),h.css({top:a.top+(void 0==d?(e-20)/2:d),left:a.left+(void 0==c?(b-100)/2:c)}).appendTo($("body")));return h}return $(".loading").remove()}function datecmp(a,b,c,d,g,e){return!c||!e?0:c!=e?c<e?-1:1:!b||!g?0:b!=g?b<g?-1:1:!a||!d?0:a!=d?a<d?-1:1:0}
function formatYMD(a){var b=a.getFullYear(),c=a.getMonth()+1,a=a.getDate();10>a&&(a="0"+a);10>c&&(c="0"+c);return b+"-"+c+"-"+a}function parseYMD(a){a=a.split("-");return new Date(a[0],parseInt(a[1],10)-1,parseInt(a[2]))}function myParseInt(a){if(parseInt(a)===a)return a;for(var b="0",c=0;c<a.length&&"0"==a[c++];);c<=a.length&&(b=a.substr(c-1));return parseInt(b)}
function preventSelection(a){function b(a,b,c){a.attachEvent?a.attachEvent("on"+b,c):a.addEventListener&&a.addEventListener(b,c,!1)}function c(){window.getSelection?window.getSelection().removeAllRanges():document.selection&&document.selection.clear&&document.selection.clear()}function d(a){a=a||window.event;if(!(a.target||a.srcElement).tagName.match(/INPUT|TEXTAREA/i)){var b=a.keyCode||a.which;a.ctrlKey&&65==b&&(c(),a.preventDefault?a.preventDefault():a.returnValue=!1)}}var g=!1;b(a,"mousemove",
function(){g&&c()});b(a,"mousedown",function(a){a=a||window.event;g=!(a.target||a.srcElement).tagName.match(/INPUT|TEXTAREA/i)});b(a,"mouseup",function(){g&&c();g=!1});b(a,"keydown",d);b(a,"keyup",d)};
// Input 3
var errorHandler={library:{},loadLibrary:function(a,b){$.ajax({url:"/api.php",data:{handler:"error_library",method:"load_library","package":a},dataType:"json",success:function(c){errorHandler.library[a]=c;void 0!=b&&b()},error:function(a,b){debug(a,b)}})},handle:function(a,b){try{void 0==this.library[a]&&this.loadLibrary(a,function(){var c=errorHandler.library[a][b];debug("[error-handler.js] "+a+"."+b+" occured");debug("[error-handler.js] Error text: "+c.text);void 0!=c.callback&&(debug("[error-handler.js] Built-in error callback found"),
c.callback=eval("("+c.callback+")"),debug("[error-handler.js] Built-in error callback called"),c.callback(),debug("[error-handler.js] Built-in error callback finished"));var g=errorHandler.library[a].handleError;if(g)try{g=eval("("+g+")"),debug("[error-handler.js] Default handler called"),g(b,c),debug("[error-handler.js] Default handler finished")}catch(e){}})}catch(c){debug(c)}}};
$(document).ready(function(){try{var a=getAnchorParam("error");if(null!=a){var b=a.split(".");errorHandler.handle(b[0],b[1])}}catch(c){debug("[error-handler.js] "+c)}});
// Input 4
function Selector(a){var b={content:[],editable:!1,enabled:!0,maxOptionsCount:5,onChange:function(){},onSelect:function(){},onSlideDown:function(){},onSlideUp:function(){}};$.extend(b,a);var a=b,c=document.createElement("div");c.className="ui-selector";var d=document.createElement("div");c.appendChild(d);var g=document.createElement("div");c.appendChild(g);var e=a.editable?document.createElement("input"):document.createElement("div");d.appendChild(e);a.editable||$(e).click(function(){f.enabled&&($(g).data("shown")?
f.hideOptions():f.showOptions())});var h=document.createElement("div");h.className="ui-options";var f={optionsArea:h,slideButton:g,inputField:e,selectedId:null,content:[],editable:a.editable,enabled:a.enabled,data:function(a,b){return void 0==b?$(this.optionsArea).data(a):$(this.optionsArea).data(a,b)},appendTo:function(a){a instanceof Element?(a.appendChild(c),a.appendChild(h)):(a.append(c),a.append(h));return this},setWidth:function(a){$(c).width(a);$(h).width(a);$(d).width(a-20);return this},setHeight:function(a){$(c).height(a);
$(d).height(a);return this},select:function(a){a=this.data("id_"+a);this.editable?$(e).val(a.value):$(e).html(a.value);this.selectedId=a.id;return this},addOption:function(b){var c=document.createElement("div");c.innerHTML=void 0!=b.html?b.html:b.value;$(c).data("id",b.id);$(c).data("value",b.value);this.data("id_"+b.id,b);$(c).click(function(){a.editable?($(e).val($(this).data("value")),$(this).data("value")):$(e).html($(this).data("value"));f.onSelect($(this).data("id"))});this.optionsArea.appendChild(c);
this.content.push(b);this.content.length>a.maxOptionsCount?($(this.optionsArea).height(a.maxOptionsCount*$(c).height()),$(this.optionsArea).css("overflow-y","scroll")):($(this.optionsArea).css("height","auto"),$(this.optionsArea).css("overflow-y","auto"));return this},setOptions:function(a){this.content=[];$(this.optionsArea).children().remove();for(var b=0;b<a.length;b++)this.addOption(a[b]);return this},hideOptions:function(){$(this.slideButton).data("shown")&&($(this.optionsArea).slideUp("fast"),
$(this.slideButton).data("shown",!1),a.onSlideUp());return this},showOptions:function(){$(this.slideButton).data("shown")||($(this.optionsArea).slideDown("fast"),$(this.slideButton).data("shown",!0),a.onSlideDown());return this},onChange:function(){a.onChange(this,$(e).val());this.showOptions();return this},onSelect:function(b){a.onSelect(b);this.selectedId=b;this.hideOptions();return this},val:function(a){return void 0!=a?this.selectedId=a:this.selectedId},enable:function(){this.enabled=!0;this.editable&&
(this.inputField.disabled=!1);return this},disable:function(){this.enabled=!1;this.editable&&(this.inputField.disabled=!0);return this},clear:function(){this.selectedId=!1;$(e).val("");return this}};f.editable&&($(e).keyup(function(){if(f.enabled)f.onChange()}),$(e).blur(function(){f.enabled&&f.hideOptions()}),$(e).focus(function(){f.enabled&&f.showOptions()}));!f.enabled&&f.editable&&(e.disabled=!0);for(b=0;b<a.content.length;b++)f.addOption(a.content[b]);b=$(g);b.data("shown",!1);$(f.optionsArea).hide();
b.click(function(){f.enabled&&($(this).data("shown")?f.hideOptions():f.showOptions())});return f}
function DynamicSelector(a){a.content=void 0!=a.content?a.content:[];a.enabled=void 0!=a.enabled?a.enabled:!0;a.maxOptionsCount=void 0!=a.maxOptionsCount?a.maxOptionsCount:5;a.onSlideDown=void 0!=a.onSlideDown?a.onSlideDown:function(){};a.onSlideUp=void 0!=a.onSlideUp?a.onSlideUp:function(){};a.onSelect=void 0!=a.onSelect?a.onSelect:function(){};a.onChange=void 0!=a.onChange?a.onChange:function(){};for(var b=a.content,c=[],d=0;d<b.length;d++)c.push(b[d].value.toLowerCase());var g=new SuffixTree(c),
e=new Selector({content:a.content,editable:!0,enabled:a.enabled,maxOptionsCount:a.maxOptionsCount,onSlideDown:a.onSlideDown,onSlideUp:a.onSlideUp,onSelect:a.onSelect,onChange:function(c,d){for(var d=d.toLowerCase(),e=g.getPossibleIndexes(d),m=[],n=0;n<e.length;n++)m.push(b[e[n]]);c.setOptions(m);a.onChange(d)}});return{appendTo:function(a){e.appendTo(a);return this},setWidth:function(a){e.setWidth(a);return this},val:function(){return e.val()},select:function(a){e.select(a);return this},disable:function(){e.disable();
return this},enable:function(){e.enable();return this},clear:function(){e.clear();return this},text:function(){return e.inputField.value}}}
function FadingImage(a){var b={src:"../images/delete.png",CSSClass:"",animationSpeed:400,minOpacity:0.35,onclick:function(){debug("action is not defined!")}};$.extend(b,a);var a=b,c=$("<img/>",{src:a.src}).hover(function(){$(this).animate({opacity:1},a.animationSpeed)},function(){$(this).animate({opacity:a.minOpacity},a.animationSpeed)}).addClass(a.CSSClass).css({opacity:a.minOpacity,cursor:"pointer"}).click(a.onclick);return{appendTo:function(a,b){c.appendTo(a instanceof jQuery?a:$("#"+a));void 0!=
b&&(b instanceof jQuery?b:$("#"+b)).hover(function(){c.show()},function(){c.hide()});return this},hide:function(){c().hide();return this},show:function(){c().show();return this}}}
function FadingButton(a){var b={html:"\u041a\u043d\u043e\u043f\u043a\u0430",animationSpeed:400,minOpacity:0.35,CSSClass:"",css:{},onclick:function(){debug("action is not defined!")}};$.extend(b,a);var a=b,c=$("<div/>").addClass(a.CSSClass).html("<div>"+a.html+"</div>").css({opacity:a.minOpacity,cursor:"pointer"}).css(a.css).click(a.href?function(){window.location=a.href}:a.onclick),d=function(){c.hover(function(){$(this).animate({opacity:1},a.animationSpeed)},function(){$(this).animate({opacity:a.minOpacity},
a.animationSpeed)})};d();return{appendTo:function(a,b){c.appendTo(a instanceof jQuery?a:$("#"+a));void 0!=b&&(b instanceof jQuery?b:$("#"+b)).hover(function(){c.show()},function(){c.hide()});return this},hide:function(){c.hide();return this},show:function(){c.show();return this},css:function(a){c.css(a);return this},enable:function(){c.click(a.onClick).css({cursor:"pointer",opacity:a.minOpacity});d();return this},disable:function(){c.unbind().css({cursor:"default",opacity:a.minOpacity});return this},
content:function(a){var b="jQuery"==typeof a?a:$("<div/>").html(a);c.children().fadeOut("fast",function(){b.hide();c.append(b);b.fadeIn()});return this},click:function(a){void 0==a?c.click():c.unbind("click").click(a);return this}}}
function AddCupPanel(a){if(void 0==a.compId)debug("comp_id in AddCupPanel is undefined!!");else{var b={parentCupId:0,onCancel:function(){}};$.extend(b,a);var a=b,c=$("<div/>",{id:"create_cup_panel"}),d=$("<input/>",{id:"create_cup_name",type:"text",value:0!=a.parentCupId?"\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0434\u043b\u044f \u0442\u0443\u0440\u043d\u0438\u0440\u0430":"\u0422\u0443\u0440\u043d\u0438\u0440"}).addClass("create_cup_content");0!=
a.parentCupId?d.focus(function(){"\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0434\u043b\u044f \u0442\u0443\u0440\u043d\u0438\u0440\u0430"==d.val()&&d.val("\u0413\u0440\u0443\u043f\u043f\u0430 ").css("color","black")}).blur(function(){""==d.val()&&d.val("\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0434\u043b\u044f \u0442\u0443\u0440\u043d\u0438\u0440\u0430").css("color","gray")}):d.attr("disabled",
"disabled");var b=$("<div/>").addClass("create_cup_content"),g=new Selector({content:[{id:"playoff",value:"\u043a\u0443\u0431\u043e\u043a \u043f\u043e \u043e\u043b\u0438\u043c\u043f\u0438\u0439\u0441\u043a\u043e\u0439 \u0441\u0438\u0441\u0442\u0435\u043c\u0435"},{id:"one-lap",value:"\u0447\u0435\u043c\u043f\u0438\u043e\u043d\u0430\u0442 \u0432 \u043e\u0434\u0438\u043d \u043a\u0440\u0443\u0433"},{id:"two-laps",value:"\u0447\u0435\u043c\u043f\u0438\u043e\u043d\u0430\u0442 \u0432 \u0434\u0432\u0430 \u043a\u0440\u0443\u0433\u0430"}]});
g.setWidth(240);g.select(0==a.parentCupId?"playoff":"one-lap");g.appendTo(b);var e=$("<input/>",{type:"button",value:"\u0421\u043e\u0437\u0434\u0430\u0442\u044c"}).addClass("create_cup_content").click(function(){cup.createCup(a.compId,a.parentCupId,d.val(),g.val(),function(){c.slideUp(a.speed)})}),h=$("<input/>",{type:"button",value:"\u041e\u0442\u043c\u0435\u043d\u0430"}).addClass("create_cup_content").click(function(){c.slideUp(a.speed,function(){a.onCancel()})});c.append(d);c.append(b);c.append(e);
c.append(h);c.hide();void 0!=a.container&&c.appendTo($("#"+a.container));return{slideDown:function(){c.slideDown(a.speed,a.callback);d.focus();return this},slideUp:function(){c.slideUp(a.speed,a.callback);return this},hide:function(){c.hide();return this},show:function(){c.show();return this},appendTo:function(a){c.appendTo($("#"+a));return this}}}}
function CheckBox(a){var b={onCheck:function(){},id:0};$.extend(b,a);var c=ce("div");$(c).addClass("checkbox");$(c).click(function(){$(this).hasClass("on")?($(this).removeClass("on"),b.onCheck(!1,b.id)):($(this).addClass("on"),b.onCheck(!0,b.id))});return{id:b.id,state:!1,appendTo:function(a){a.append(c);return this},setState:function(a){void 0!=a&&(a?($(c).addClass("on"),b.onCheck(!0)):($(c).removeClass("on"),b.onCheck(!1)));return this.state}}}
function Button(a){var b={onClick:function(){},container:null,CSSClass:"",html:"Text"};$.extend(b,a);var a=b,c=$("<div/>").addClass(a.CSSClass).addClass("default_button").click(a.onClick).append($("<div/>").addClass("button_inner").html(a.html));null!=a.container&&(a.container instanceof jQuery?a.container:$("#"+a.container)).append(c);return{enable:function(){c.click(a.onClick);return this},disable:function(){c.unbind("click",a.onClick);return this},appendTo:function(a){(a instanceof jQuery?a:$("#"+
a)).append(c);return this}}}
function PeopleListItem(a){var b={targetId:0,personId:0,personName:"undefined",onClick:function(){},canDelete:!1};$.extend(b,a);var a=b,b=$("<li/>",{id:"person_"+a.personId}).addClass("leaf").appendTo(".people").fadeIn("slow"),c=$("<div/>").appendTo(b);$("<div/>",{text:a.personName}).appendTo(c);c=$("<div/>",{id:"person_"+a.personId+"_image"}).appendTo(c);$("<div/>").addClass("clear").appendTo(b);a.canDelete&&FadingImage({CSSClass:"fading_image",onclick:function(b){a.onClick(a.personId,a.targetId);
b.stopPropagation()}}).appendTo(c,b);peopleSelector.clear();return b}
function PopUp(a){var b={x:690,y:200,html:"DefaultHTML",id:tm()+"_"+Math.round(1E3*Math.random()),delay:200};$.extend(b,a);a=b;void 0==a.recalcCoords&&(a.recalcCoords=function(){return{x:a.x,y:a.y}});var c=$("<div/>").addClass("popup_box").hide(),d=$("<div/>"),g=$("<div/>").addClass("popup_box_arrow_down");d.html(a.html);c.append(d).append(g);c.css({top:a.y-c.outerHeight()+"px",left:a.x-c.outerWidth()/2+"px",zIndex:69});g.css({top:c.outerHeight()-4+"px",left:c.outerWidth()/2-5+"px",zIndex:70});c.attr("id",
a.id).data("over",!1);$("body").append(c);b={__options:a,position:function(a,b){c.css({top:b-c.innerHeight()+"px",left:a-c.outerWidth()/2+"px"});g.css({top:c.outerHeight()-4+"px",left:c.outerWidth()/2-5+"px"});return this},show:function(){var b=a.recalcCoords(a.id);this.position(b.x,b.y);c.fadeIn();return this},hide:function(){var b=c.attr("id");setTimeout(function(){$("#"+b).data("over")||$("#"+b).fadeOut().data("over",false)},a.delay);return this},append:function(a){d.append(a);return this}};c.hover(function(){$(this).data("over",
true)},function(){$(this).data("over",false);$(this).fadeOut()});return b}
function DateSelector(a){var b=a.date,c=a.onSelect?a.onSelect:function(){},d=a.anchor?a.anchor:!1,g=a.select?a.select:!1,e=a.dateChecked?a.dateChecked:function(){return""},h=b?b.split("-"):!1,f=new Date,j=myParseInt(h?h[2]:f.getDate()),m=myParseInt(h?h[1]:f.getMonth()+1),n=myParseInt(h?h[0]:f.getFullYear()),l=a.minDate||{},k=a.maxDate||{},i=tm()+"_";jContainer=$("<div/>").addClass("ui-date-selector").attr("id",i);jDate=$("<div/>").addClass("date");jGrid=$("<div/>").addClass("grid").hide();jContainer.append(jDate).append(jGrid);
var s=!1,t=function(){return n+"-"+(10<=m?m:"0"+m)+"-"+(10<=j?j:"0"+j)},u=m,o=n,v=function(a,b,c){b=b?myParseInt(b):!1;a=a?myParseInt(a):!1;return 0<=datecmp(a,b,c,l.d,l.m,l.y)&&0>=datecmp(a,b,c,k.d,k.m,k.y)?"":" off"},r=function(b,f){o=f;u=b;var h=(new Date(f,b-1,1)).getDay(),h=0==h?7:h,p,l=0==f%4?common.months[b-1].length_leap:common.months[b-1].length;p=""+('<table><thead><th class="m_h" colspan="7">'+common.months[b-1].name+"&nbsp;"+f+"</th></thead><tbody>");for(var k=0;6>k;++k){p+="<tr>";for(var r=
1;7>=r;++r){var q=7*k+r-h+1;p=1<=q&&q<=l?p+('<td class="d'+v(q,b,f)+(0==datecmp(q,b,f,j,m,n)?" selected":"")+e(q,b,f)+'">'+q+"</td>"):p+"<td></td>"}p+="</tr>";if(q>l&&5>k)break}jGrid.html(p+"</tbody></table>");$("#"+i+" .d").not(".off").bind("click",function(){var b=parseInt($(this).html()),e=u,f=o;j=myParseInt(b);m=myParseInt(e);n=myParseInt(f);b=10<=j?j:"0"+j;jDate.html(b+"&nbsp;"+common.months[m-1].name_gen+"&nbsp;"+f);c(t());a.hideOnSelect&&(jGrid.fadeOut(),s=!1);d&&setAnchorParam("date",t());
g&&($("#"+i+" .d").removeClass("selected"),$(this).addClass("selected"))});$("#"+i+" .m_h").bind("click",function(){w(o)})},w=function(a){o=a;for(var b='<table><thead><th class="y_h" colspan="4">'+a+"</th></thead><tbody>",c=0;3>c;++c){for(var b=b+"<tr>",d=0;4>d;++d)var e=4*c+d,b=b+('<td class="m'+v(void 0,e+1,a)+'" id="'+i+""+(e+1)+'">'+common.months[e].name_short+"</td>");b+="</tr>"}jGrid.html(b+"</tbody></table>");$("#"+i+" .m").not(".off").bind("click",function(){var a=$(this).attr("id").split("_")[1];
r(a,o)});$("#"+i+" .y_h").bind("click",function(){x(o)})},x=function(a){o=a;for(var a=20*Math.floor(a/20),b='<table><thead><th class="y20_h" colspan="5">'+(l.y?Math.max(a,l.y):a)+" &mdash; "+(k.y?Math.min(a+19,k.y):a+19)+"</th></thead><tbody>",c=0;4>c;++c){for(var b=b+"<tr>",d=0;5>d;++d)var e=a+5*c+d,b=b+('<td class="y'+v(void 0,void 0,e)+'" id="'+i+""+e+'">'+e+"</td>");b+="</tr>"}jGrid.html(b+"</tbody></table>");$("#"+i+" .y").not(".off").bind("click",function(){var a=$(this).attr("id").split("_")[1];
w(a)});$("#"+i+" .y20_h").bind("click",function(){y()})},y=function(){for(var a='<table><thead><th class="off" colspan="5">'+(l.y?Math.max(1900,l.y):1900)+" &mdash; "+(k.y?Math.min(2299,k.y):2299)+"</th></thead><tbody>",b=0;3>b;++b){for(var a=a+"<tr>",c=0;5>c;++c)var d=1900+20*(5*b+c),a=a+('<td class="y20 '+(l&&d+19<l.y||k&&d>k.y?" off":"")+'" id="'+i+""+d+'">'+d+" "+(d+19)+"</td>");a+="</tr>"}jGrid.html(a+"</tbody></table>");$("#"+i+" .y20").not(".off").bind("click",function(){var a=$(this).attr("id").split("_")[1];
x(a)})};b?(debug(j),jDate.html((10<=j?j:"0"+j)+"&nbsp;"+common.months[m-1].name_gen+"&nbsp;"+n)):jDate.html("\u0432\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0434\u0430\u0442\u0443");jDate.click(function(){if(s)jGrid.fadeOut();else{r(u,o);jGrid.fadeIn()}s=!s});return{appendTo:function(a){a.append(jContainer)},hideGrid:function(){jGrid.fadeOut();s=false},showGrid:function(){r(u,o);jGrid.fadeIn();s=true},val:function(){return t()},setBounds:function(a,b){var c=a.split("-"),d=b.split("-");l={y:myParseInt(c[0]),
m:myParseInt(c[1]),d:myParseInt(c[2])};k={y:myParseInt(d[0]),m:myParseInt(d[1]),d:myParseInt(d[2])}},clear:function(){}}}
function Timeline(a){var b={delta:7,centerDate:Math.floor((new Date).getTime()/864E5),commonW:30};$.extend(b,a);a=b;debug(a);for(var c=$("<div/>").addClass("ui-timeline"),d=[],b=-a.delta;b<=a.delta;++b){var g=new Date(864E5*(a.centerDate+b)),e=g.getDate(),g=d[a.delta+b]=$("<div/>").addClass("date day-"+b).html(e).data("ms",g.getTime()).appendTo(c);0==b&&g.addClass("center")}c.append($('<div class="month_name m1"></div>'));c.append($('<div class="month_name m2"></div>'));var h=[],f=function(b,e){var g=
Math.floor(b/864E5);c.children(".month_name.m2").hide();for(var f=-a.delta;f<=a.delta;++f){var i=new Date(864E5*(g+f)),j=i.getDate(),t=d[a.delta+f].html(j).data("ms",i.getTime());f==-a.delta&&c.children(".month_name.m1").css({left:t.offset().left}).html(common.monthName(i)+"'"+(new String(i.getFullYear())).substring(2));1==j&&f>-a.delta&&c.children(".month_name.m2").show().css({left:t.offset().left}).html(common.monthName(i)+"'"+(new String(i.getFullYear())).substring(2))}if(e)for(g=0;g<h.length;++g)h[g](b)},
j=function(b){var d=b.width()/(2*a.delta+1);c.children(".date").width(d-a.commonW).each(function(b){var c=2*((b-a.delta)/a.delta);$(this).css({left:b*d,opacity:Math.exp(-c*c/2)})}).click(function(){var a=$(this).data("ms");f(a,!0)});c.children(".month_name").css({width:d-a.commonW+20})};return{getByContainer:function(a){j(a);$(window).resize(function(){j($(c).parent())});return c},scrollTo:function(a){f(a,!0)},silentScrollTo:function(a){f(a)},onChange:function(a){h.push(a)}}};
// Input 5
function ToolTip(a){$.extend(!0,a,{orientation:"left",html:""});return{}}
var slideBlock={getOpenedParts:function(){return getCookie("opened_parts").split(",")},addOpenedPart:function(a){var b=getCookie("opened_parts");setCookie("opened_parts",void 0==b||""==b?""+a:getCookie("opened_parts")+","+a,365)},removeOpenedPart:function(a){for(var b="",c=this.getOpenedParts(),d=0;d<c.length;d++)c[d]!=a&&(b+=0==b.length?c[d]:","+c[d]);setCookie("opened_parts",b,365)},togglePart:function(a){$("#"+a+" > .title").hasClass("opened")?($("#"+a+" > .body").slideUp(),$("#"+a+" > .title").removeClass("opened"),
slideBlock.removeOpenedPart("#"+a)):($("#"+a+" > .body").slideDown(),$("#"+a+" > .title").addClass("opened"),slideBlock.addOpenedPart("#"+a))}};
// Input 6
var content={loadingComments:"",loadingEvaluations:"",sending:!1,loadComments:function(a,b){$.ajax({url:"/procs/proc_content.php",data:{method:"get_comments",from:5*(b-1),limit:5,item_id:a},beforeSend:function(){content.loadingComments=a+"_"+b},success:function(c){content.loadingComments==a+"_"+b&&($("#comments_"+a).find(".comments_content").html(c),content.loadingComments="")}})},loadInitialComments:function(a,b){$.ajax({url:"/procs/proc_content.php",data:{method:"get_initial_comments",item_id:a,
t:tm()},beforeSend:function(){content.loadingComments=a+"_"},success:function(c){content.loadingComments==a+"_"&&(b.html(c),content.loadingComments="")}})},sendComment:function(a){if(!content.sending){var b=$("#comments_"+a),c=b.find("textarea").val();""!=c&&$.ajax({url:"/procs/proc_content.php",data:{method:"add_comment",text:c,item_id:a},dataType:"json",beforeSend:function(){content.sending=!0},success:function(c){"ok"==c.status&&(b.find("textarea").val(""),content.loadComments(a,Math.ceil(c.count/
5)),content.sending=!1)}})}},ctrlEnterHandler:function(a,b){a.ctrlKey&&(10==a.keyCode||13==a.keyCode)&&b()},loadEvaluation:function(a,b){$.ajax({url:"/procs/proc_content.php",data:{method:"get_evaluations",item_id:b,t:tm()},dataType:"json",beforeSend:function(){content.loadingEvaluations=b},success:function(c){content.loadingEvaluations==b&&(a.html(""),content.showEvaluation(a,b,c.avg,c.is_evaluable),content.loadingEvaluations="")}})},showEvaluation:function(a,b,c,d){if(d)for(c=0;5>c;c++)a.append($("<div/>").addClass("star_empty").attr({id:"value_"+
(c+1)}).css({cursor:"pointer"}).mouseover(function(){var b=$(this).attr("id").split("_")[1];a.children("div").each(function(a,c){a<b&&$(c).removeClass("star_empty").addClass("star_solid")})}).mouseout(function(){a.children("div").removeClass("star_solid").addClass("star_empty")}).click(function(){var a=$(this).attr("id").split("_")[1];content.evaluateItem(b,a)}));else{a.attr({title:"\u041e\u0446\u0435\u043d\u043a\u0430: "+Math.round(100*c)/100});c=Math.round(c);for(d=0;d<c;d++)a.append($("<div/>").addClass("star_solid"));
for(c=d;5>c;c++)a.append($("<div/>").addClass("star_empty"))}},evaluateItem:function(a,b){$.ajax({url:"/procs/proc_content.php",data:{method:"evaluate",item_id:a,value:b},dataType:"json",success:function(b){if("ok"!=b.status)return!1;$(".evaluation").html("");content.showEvaluation($(".evaluation"),a,b.value,!1)}})},markAsViewed:function(a,b,c){$.ajax({url:"/procs/proc_content.php",data:{method:"mark_as_viewed",target_type:a,target_id:b},dataType:"json",success:function(d){return"ok"!=d.status&&void 0!=
c?c(a,b):!1}})},updateFreshness:function(a,b){void 0!=ge(a+"_new")?0<b?$("#"+a+"_new").html("+"+b).show():$("#"+a+"_new").html("").hide():0<b?$("#menu_"+a).append($("<div/>").attr("id",a+"_new").html("+"+b).css("display","block")):$("#menu_"+a).append($("<div/>").attr("id",a+"_new").html(""))},checkFreshness:function(){void 0!=ge("user_bar")&&$.ajax({url:"/procs/proc_fresh.php",data:{t:tm()},dataType:"json",success:function(a){if("ok"!=a.status)return!1;content.updateFreshness("forum",a.forum);content.updateFreshness("life",
a.life);setTimeout(content.checkFreshness,100<a.process_time?6E4:1E4);return!0}})},cutString:function(a,b,c,d){var d=d||"...",g=a.length;if(b>c||g<=c)return a;for(;0<=c&&!(g=a.charAt(c),"\t"==g||"\n"==g||" "==g);c--);return c<b/2?a.substr(0,b)+d:a.substr(0,c)+d},initBugReport:!1,reportBug:function(){content.initBugReport||($("<div/>").attr("id","bug_report").hide().appendTo($("#layout").parent()).append($("<textarea/>").attr("id","bug_text")).append($("<div/>").html("\u041e\u0441\u0442\u0430\u0432\u0438\u0442\u044c \u043e\u0442\u0437\u044b\u0432").addClass("button").one("click",
content.sendBug)),$("body").keypress(function(a){debug(a.which);27==a.which&&content.cancelBug()}),content.initBugReport=!0);$("#layout").fadeOut(function(){$("#bug_report").fadeIn()})},cancelBug:function(){$("#bug_report").fadeOut(function(){$("#layout").fadeIn()})},sendBug:function(){var a=$("#bug_text").val();$.ajax({url:"/procs/proc_content.php",data:{method:"report_bug",text:a,page:window.location.pathname},dataType:"json",success:function(a){a&&a.status&&"ok"==a.status?($("#bug_report").html("<center>OK</center>"),
window.location=a.topic):$("#bug_report").html("<center>ERROR</center>");content.cancelBug()}})},showTags:function(a,b,c){var c=$(c),d;for(d in a){var g=a[d],e=b.replace("%d",g.id);content.showTag(e,g.value,g.id,c)}},showTag:function(a,b,c,d){a=$("<a/>",{href:a}).appendTo(d);$("<div/>",{"class":"tag",id:"tag"+c,text:b}).appendTo(a)}};$(function(){content.checkFreshness()});
// Input 7
var mainMenu={passiveColor:"",activeColor:"",openedColor:"",initColors:function(){this.passiveColor=COLOR.FIRST;this.activeColor=COLOR.THIRD;this.openedColor=COLOR.SECOND},openedMenuId:null,openedSubmenuId:null,selectedMenuId:null,selectedSubmenuId:null,selectOpened:function(){this.selectMenu($("#"+this.openedMenuId));this.selectSubmenu($("#"+this.openedSubmenuId))},selectMenu:function(a){if(null!=a&&(this.openedMenuId==a.attr("id")?this.selectSubmenu($("#"+this.openedSubmenuId)):this.selectSubmenu(null),
this.selectedMenuId!=a.attr("id"))){var b=this.selectedMenuId;this.selectedMenuId=a.attr("id");var c=a.attr("id"),d=this.activeColor;c==this.openedMenuId&&(d=this.openedColor);this.selectedMenuId==c&&a.animate({backgroundColor:d},100,"linear",function(){mainMenu.selectedMenuId!=b&&$("#"+b).animate({backgroundColor:mainMenu.passiveColor},100,"linear")});$("#menu_detach_bar").animate({backgroundColor:d},100,"linear",function(){mainMenu.selectedMenuId!=b&&$("#submenu_"+b.split("_")[1]).slideUp(100,function(){$("#"+
mainMenu.selectedSubmenuId).css({backgroundColor:mainMenu.passiveColor});$("#"+mainMenu.openedSubmenuId).css({backgroundColor:mainMenu.openedColor});mainMenu.selectedSubmenuId=mainMenu.openedSubmenuId;c==mainMenu.selectedMenuId&&$("#submenu_"+c.split("_")[1]).slideDown(100)})})}},selectSubmenu:function(a){if(null==a){var b=this.selectedSubmenuId;this.selectedSubmenuId=null;$("#"+b).animate({backgroundColor:mainMenu.passiveColor},100,"linear")}else if(this.selectedSubmenuId!=a.attr("id")){b=this.selectedSubmenuId;
this.selectedSubmenuId=a.attr("id");var a=a.attr("id"),c=this.activeColor;this.selectedMenuId==this.openedMenuId&&(c=this.openedColor);void 0!=a&&this.selectedSubmenuId==a&&this.selectedMenuId==$("#"+a).parent().parent().attr("id").split("sub")[1]?$("#"+a).animate({backgroundColor:c},100,"linear",function(){mainMenu.selectedSubmenuId!=b&&$("#"+b).animate({backgroundColor:mainMenu.passiveColor},100,"linear")}):this.selectedSubmenuId!=b&&$("#"+b).animate({backgroundColor:mainMenu.passiveColor},100,
"linear")}},alignSubmenus:function(){for(var a=$("#submenu_container").offset().left,b=$("#submenu_container").innerWidth(),c=["index","sport","media","life"],d=0;d<c.length;d++){var g=$("#submenu_"+c[d]).innerWidth(),e=$("#menu_"+c[d]).offset().left,h=$("#menu_"+c[d]).outerWidth(),e=e-a+h/2-g/2,e=0>e?0:e;a+e+g<a+b?$("#submenu_"+c[d]).css("left",e):$("#submenu_"+c[d]).css("right",0)}}};
$(document).ready(function(){mainMenu.initColors();mainMenu.openedMenuId=$("#menu_container a div.opened").attr("id");mainMenu.openedSubmenuId=$("#submenu_container div a div.opened").attr("id");mainMenu.selectedMenuId=mainMenu.openedMenuId;mainMenu.selectedSubmenuId=mainMenu.openedSubmenuId;$(document).mouseout(function(a){"menu"==$(a.fromElement).attr("id")&&mainMenu.selectOpened()});$("body").mouseover(function(){mainMenu.selectOpened()});$("#menu").mouseout(function(a){a.stopPropagation()});$("#menu").mouseover(function(a){a.stopPropagation()});
$("#menu_container a div.menu_item").mouseover(function(){mainMenu.selectMenu($(this))});$("#submenu_container a div.submenu_item").mouseover(function(){mainMenu.selectSubmenu($(this))})});$(document).ready(mainMenu.alignSubmenus);$(window).resize(mainMenu.alignSubmenus);
// Input 8
function showError(a,b){alert(b)}function showErrorXML(a){alert($(a).text())}function showErrorJSON(a){alert(a)}function showErrorText(a){alert(a)};
// Input 9
var main={photobg:{randomize:function(a){api.request({handler:"photobg",method:"get",success:function(b){void 0!=a&&a();for(var c=Math.floor(b.images.length*Math.random()),d=0;b.images[c].url==getCookie("photobg_url")&&10>d;)c=Math.floor(b.images.length*Math.random()),d++;b=b.images[c];c=$("<div/>").addClass("photobg").css("max-width",b.w+"px").hide().append($("<img/>").attr("src",b.url));"1"==b.right_side&&c.addClass("right");$("#layout").append(c);c.fadeIn();setCookie("photobg_url",b.url,1)}})}},
showErrorText:function(a){$("#error_box").html(a).slideDown().delay(5E3).slideUp()},showNotification:function(a){var b=$("<div/>",{"class":"custom_alert"}).hide().appendTo($("html"));a instanceof $?a.appendTo(b):($("<div/>",{"class":"custom_alert_text",html:a}).appendTo(b),$("<div/>",{"class":"custom_alert_btn button",text:"Ok"}).appendTo(b).click(function(){b.fadeOut("fast",function(){$("body").fadeTo("fast",1);b.remove()})}));b.css({"margin-left":"-"+b.width()/2+"px","margin-top":"-"+b.height()/
2+"px"});$("body").fadeTo("fast",0.4,function(){b.fadeIn("fast")})}};$(main.photobg.randomize);
